---
title: 'Class 06: R function'
author: "Luan Tran"
date: "4/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About
This is my **class 6** r markdown document with my *code* and notes for the day.

```{r}
plot(1:10, typ="l", col="blue")
```

```{r}
read.table("test1.txt", header = TRUE, sep=",")
```

```{r}
read.csv("test1.txt")
```
```{r}
read.table("test2.txt", header = TRUE, sep="$")
```
```{r}
read.table("test3.txt")
```

Functions

```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y
}

```

```{r}
add (x=c(1,2,3, y=4))
```
```{r}
rescale <- function(x) {
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}


```

# Test on a small example where you know the answer
```{r}
rescale(1:10)
```


# How would you get your function to work here…

```{r}
rescale( c(1,2,NA,3,10) )
```

```{r}
x <-  c(1,2,NA,3,10)
rng <- range(x, na.rm = TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])
```
```{r}
rescale2 <- function(x, na.rm=TRUE) {
  
  if(!is.numeric(x)) {
    stop("You need to give only numbers please")
    
  }
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}

```


```{r}
#rescale2(c(1,10,"string"))
```


```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")
 
 if(plot) {
    plot(answer, typ="b", lwd=4)
    print("Please don't sing again")
 }
 
 print("I can see it in ...")
 return(answer)
}
```



```{r}
rescale3( c(1,3,NA,10), plot = TRUE)
```


```{r}
x <- c(1,10,"string")

is.numeric(x)
#range(x, na.rm = )
```

